# Generated by Django 2.1.5 on 2024-03-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink_app', '0002_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Posts/Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='releaseDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
