# Generated by Django 2.1.5 on 2024-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink_app', '0006_auto_20240317_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likeID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
