# Generated by Django 2.1.5 on 2024-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink_app', '0008_auto_20240317_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures'),
        ),
    ]
