# Generated by Django 2.1.5 on 2024-03-22 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blink_app', '0009_auto_20240319_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
