# Generated by Django 2.1.5 on 2024-03-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blink_app', '0010_auto_20240321_2020'),
        ('blink_app', '0010_auto_20240322_0157'),
    ]

    operations = [
    ]
